config:
  categories:
  - crypto
  - web
  - forensics
  - misc
  - re
  - pwn
  - osint
  difficulties:
  - name: easy
    value: 1000
  - name: medium
    value: 1000
  - name: hard
    value: 1000
  - name: insane
    value: 1000
  name: LNC2024
  port: 8000
  port_mappings:
    CtfChallengeHub:
      from_port: '1337'
      to_port: '8401'
    InversXin:
      from_port: '5000'
      to_port: '8402'
    Orwells_Firewall:
      from_port: '5000'
      to_port: '8100'
    This_WEB_Too_Simple:
      from_port: '5000'
      to_port: '8103'
    apache-server:
      from_port: '80'
      to_port: '8101'
    bit-collider:
      from_port: '1337'
      to_port: '8000'
    cheminventory:
      from_port: '1337'
      to_port: '8400'
    dhi_or_dlo:
      from_port: '1337'
      to_port: '8001'
    luckyplaza:
      from_port: '1688'
      to_port: '8403'
    poisoned:
      from_port: '1340'
      to_port: '8404'
    racket-server:
      from_port: '8014'
      to_port: '8200'
    reverse-proxy:
      from_port: '80'
      to_port: '8102'
    wabbit:
      from_port: '8888'
      to_port: '8300'
    welcome:
      from_port: '1337'
      to_port: '8405'
