FROM php:8.1-apache

RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini" && \
    sed -i 's/^log_errors = On$/log_errors = Off/' "$PHP_INI_DIR/php.ini"
RUN /usr/sbin/useradd --no-create-home -u 1000 user
RUN chmod -R =rx /var/www/html/

COPY src/index.php /var/www/html/index.php
COPY src/files /var/www/html/files
COPY src/flag.txt /flag.txt
RUN chmod 777 /var/www/html/files/1d788013b9c73e1dead5b9758b56b9dd.txt

USER user
CMD ["/bin/sh", "-c", "php -S 0.0.0.0:5000"]